name: Testing client workflow [lint & build]
on: 
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        working-directory: ./src/client
        run: npm ci
      - name: Application building
        working-directory: ./src/client
        run: npm run build
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        working-directory: ./src/client
        run: npm ci
      - name: Code linting
        working-directory: ./src/client
        run: npm run lint
